### PR TITLE
Proposal: Let's provide container images

### PR DESCRIPTION
**Pull request by pauvos**
I run wikiless on raspberry k3s and I would like to have linux/arm64 compatible images in some registry.

This adds a github action to build and publish latest and semver tags to `ghcr.io/Metastem/wikiless`.

Note: run condition still needs to be changed:
```yaml
on:
  push:
    branches: ["buildx"] # replace with main
```

Test pipelines:
https://github.com/pauvos/wikiless/actions/workflows/build-image.yml

Container images:
https://github.com/pauvos/wikiless/pkgs/container/wikiless

### CODE REVIEW

**Comment by itsokk** [comment]
`npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /app/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-13T17_48_36_661Z-debug-0.log`
This happens when running the image.
Am i supposed to clone this repo and mount the files? Why would i do this? Isn't that the purpose of docker containers to pack everything into a docker image?

**Comment by itsokk** [comment]
@pauvos @Metastem

**Comment by pauvos** [comment]
@itsokk , sorry for the inconvenience. The image expects the application to be in /wikiless , but the docker-compose.yml isn't up to date and still mounts to directory /app.

I checked the history of Dockerfile (https://github.com/Metastem/wikiless/commit/4b2d09237a81dcffcc886efee378484ce70a0217) and the application moved from /app to /wikiless in May.

I'll create a pull request with a docker-compose fix.

**Comment by pauvos** [comment]
@itsokk , new pull request #11 to fix the docker-compose.yml

**Pull request merged**
